###########################################################
# Service de gestion du revers Proxy pour le developpement
# doc => https://hub.docker.com/r/ubuntu/nginx
# doc lateste => https://hub.docker.com/_/nginx
###########################################################
version: '3.8'

services:

  ######################################################
  # configuration NGINX Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: NGINX-Dev
    restart: always
    ports:
      - 80:80
      - 88:88
      - 99:99
      - 90:90
      - 443:443

    environment:
      - TZ=Europe/Paris

    volumes:
      - ./nginx-dev/html:/usr/share/nginx/html
      - ./nginx-dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/maxime/projet/blog/upload-site:/usr/share/nginx/images